### ISSUE TITLE
[Use case] Aircraft trajectories

### ISSUE THREAD

**Issue by espinielli** [mablab/sftrack#14]
**Use case:**
The massive availability of crowdsourced [ADS-B][adsb] position reports from parties such as
[flightradar24][fr24] (commercial), [FlightAware][fa] (commercial), [ADSBx][ae] (free for non-commercial/research) or [OpenSky Network][osn] (free for reseach) makes it possible to study 4D aircraft trajectories with an unprecedented spatial coverage and accuracy.

[adsb]: <https://en.wikipedia.org/wiki/Automatic_dependent_surveillance_%E2%80%93_broadcast> "ADS-B Wikipedia"
[fr24]: <https://www.flightradar24.com/> "flightradar24"
[fa]: <https://flightaware.com/> "FlightAware"
[ae]: <https://www.adsbexchange.com> "ADSBExchange"
[osn]: <https://opensky-network.org/> "OpenSky Network"

**Requirements:**
What are the technical requirements needed to achieve this use case. I.e an ordered time series and a set of geographic coordinates are required to plot a trajectory.

**Input:**
Aircraft regularly report data such as:
* longitude
* latitude
* aircraft ID
* callsign
* ground speed
* timestamp (indirectly as recorded by the receiving station)

Of interest are also (elementary) airspaces, typically described by a (ground) polygon and minimum and maximum altitude.

**Output:**
Given the position reports associated to aircraft and the airspaces in the region of interest it would be great to be able to spatially filter the portion of flights intersecting them

**Additional information:**
Some work on trajectories for aviation is done in R in the [{`trrrj`}][trrrj] package and in Python in the [`traffic`][traffic] library.

[trrrj]: <https://github.com/euctrl-pru/trrrj> "trrrj package (R)"
[traffic]: <https://github.com/xoolive/traffic> "traffic library (Python)"

**Comment by birderboone** [comment]
Thank you for your submission.

In many ways as a plane trajectory should look, in the x,y, t directions, the data should look similar to a standard terrestrial trajectory and we expect sftrack to fit in with these similar goals largely because of sf and rgdal integration. At current, we are still struggling with the limited scope of calculations in the 3rd dimension because of `rgdal` lacking that functionality. We're trying to look into all the best tools available to us for 3d calculations and what seems feasible. Thanks for the `trrrj` package, I'll look into it and see their solution.

Thanks!

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
