### ISSUE TITLE
build pkgdown website

### ISSUE THREAD

**Issue by pratikunterwegs** [mablab/sftrack#26]
Hi, I was trying to install `sftrack` with its vignettes and the vignettes failed to build (because dependencies on my side).

That got me thinking about whether you could add a [`pkgdown`](https://pkgdown.r-lib.org/) website which would have the built vignettes as htmls, as well as a neat reference sheet for all the functions.

It's quite painless with `pkgdown` and helps a ton.

**Comment by basille** [comment]
Hi @pratikunterwegs, I can answer that one! Yes, this is already planned, as we did for [`rpostgis`](https://mablab.org/rpostgis/) for instance. We're still working on documentation a lot — the vignettes are part of it, and some of them still require heavy lifting. Hopefully this should all be ready by the time of CRAN submission. 

In the meanwhile, if you're sure that the problem comes from your end (otherwise please submit a bug issue), I would suggest that you simply clone the repository locally, and browse the RMarkdown vignettes directly — you'll be able to interact with the code much more nicely than with the static HTML vignettes.

Thanks for you interest in our package!

**Comment by pratikunterwegs** [comment]
Ah, alright. Yes the problem was on my end with `adehabitatLT` missing.
