### ISSUE TITLE
[Use case] Differentiate between point-based and segment-based attributes

### ISSUE THREAD

**Issue by jedalong** [mablab/sftrack#6]
**Use case:**
In, for example adehabitat (other packages take a similar approach I believe), attributes are associated with points (i.e., each row is a GPS point). However, many attributes we are interested in are associated with segments (e.g., consecutive pairs of points). Clearly distinguishing these elements I believe is crucial for a new tracking data model.

**Requirements:**
The object clearly differentiates between point-based and segment-based attributes, through separate slots/attributes/geometries.

**Input:**
a dataframe of sftraj object.

**Output:**
sftraj object 
maybe an sftraj can be decomposed into sftraj_points and sftraj_segments (whatever you want to call it)

**Additional information:**
Making clear the distinction between point-based and segment-based attributes should improve consistency and clarity in subsequent analyses and visualizations. For example, visualizing point-based temperature values vs segment-based speed estimates. Proper treatment of gaps in the data will then also be very important, and would make the data model more generalizable with, for example, human GPS tracking studies.

**Comment by basille** [comment]
Thanks Jed for this use case! This is actually the basis of the work behind `sftraj`, and it's going to be tricky. Actually, we've been thinking about it while working on the proposal (see for instance [this discussion](https://github.com/mablab/sftraj-proposal/issues/1)). At the moment, we're actually thinking of having a dual representation of tracking data (both points and steps), with conversions in between the two — but that's not final, and I'm not sure there's an easy solution which comes with all benefits.

But however we do it, we indeed need to identify the context of ancillary data (associated to point or step). One approach might be to rely (or extend) on the `agr` attribute of `sf` objects (see [here for more details](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html#how_attributes_relate_to_geometries)). I don't know how much this is actually used by `sf` and other packages though… but could be worth checking and using, instead of reinventing the wheel.

(I'm closing this issue because we have the information necessary to work on this, i.e. requirements, but feel free to add more of your thoughts about it below!)


EDIT: I did not think of implications for plotting, but it's actually very clear that there are strong implications there! No way we can plot point attributes along step/lines…

**Comment by jedalong** [comment]
Hadn't seen that thread, yes that is a more detailed discussion of some of the issues I am thinking about, wonderful and good luck! I would also re-emphasize the point that to be a truly universal trajectory data model it should be appropriate beyond wildlife tracking applications. One thing is the data sizes (for example lots of human tracking datasets have millions and millions of GPS points from many individuals e.g., geolife), but its true that wildlife ecology may be moving closer to this with ICARUS.

**Comment by basille** [comment]
Indeed! We are trying to abstract it to a low level, i.e. movement data and trajectories — which are not necessarily wildlife tracking data! There is more and more data from humans… Performance on large datasets (as also seen [in this thread](https://github.com/mablab/sftraj/issues/2)) will be key.

**Comment by birderboone** [comment]
I'm re-opening some of these use-cases so theyre easier to find as people submit new ones.

**Comment by basille** [comment]
Closing this issue now that `sftrack` is developed and on CRAN.
